### ISSUE TITLE
Allow color spectrum selection

### ISSUE THREAD

**Issue by dhowland** [marcusolsson/grafana-treemap-panel#1]
It seems the only color assignment available is white->green.  This doesn't look great, especially when combined with white text.

Setting the color to use the text field doesn't work (it claims the text is "ambiguous").

**Comment by marcusolsson** [comment]
You're totally right, sorry about that. This is currently a limitation and I'm hoping to add support for configuring custom color spectrums to provide more customizability.

**Comment by dhowland** [comment]
The built-in table panel seems to have many gradients.  Maybe you could steal those.

How is the text field supposed to work?  Are they supposed to be color names?

**Comment by marcusolsson** [comment]
I have spectrum component from another plugin I've made that I might be able to use here as well. I know there's some work being done to add a color spectrum editor to the `grafana/data` package, that I intend to switch over to once it's done.

The text field is used as the identifier, which should probably be made clearer. Because it's used as an ID, you can't have more than one occurrence of a value. This could probably use a better error message 😅

**Comment by marcusolsson** [comment]
I've just published 0.6.0 which makes use of the new standard field option for colors. You can now change the colors to any of the color scheme currently supported by Grafana. For more information, check out the [Color scheme](https://grafana.com/docs/grafana/latest/panels/field-options/standard-field-options/#color-scheme) docs.
